name: Services - Docker build and push

on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Lowercase repository name for ghcr
      - name: Set lowercase repository name
        id: repo
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT  

      # Set up QEMU to build ARM arch on Github Action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx to build multiarch images - Automatically uses platforms fields in the Build Step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build & Push image multiarch
      - name: Build and push multiarch image
        uses: docker/build-push-action@v6
        with:
          context: ./AnimeTakusan
          file: ./AnimeTakusan/AnimeTakusan.API/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.repo.outputs.repository }}:latest
            ghcr.io/${{ steps.repo.outputs.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update image and restart container
        run: |          
          curl -s -H "Authorization: Bearer $WATCHTOWER_TOKEN" "$UPDATE_CONTAINER_URL"
        env:
          WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
          UPDATE_CONTAINER_URL: ${{ secrets.UPDATE_CONTAINER_URL }}
